# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-04 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventMate', '0002_auto_20170204_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario_evento',
            name='id_usuario',
            field=models.IntegerField(default=0),
        ),
    ]
